frontend:
  - frontend/**/*

backend:
  - app/**/*
  - migrations/**/*
  - scripts/**/*
  - requirements.txt
  - Dockerfile

database:
  - migrations/**/*
  - app/models/**/*

devops:
  - .github/**/*
  - docker-compose.yml
  - Dockerfile

documentation:
  - README.md
  - docs/**/*
  - "**/*.md"

tests:
  - tests/**/*
  - "**/test_*.py"

