# Nginx Reverse Proxy Setup for PipLinePro
# This script sets up Nginx to forward port 80 to your Flask app on port 5000
# MUST RUN AS ADMINISTRATOR

param(
    [switch]$SkipInstall
)

# Check for administrator privileges
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "ERROR: This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    exit 1
}

$NginxDir = "C:\nginx"
$NginxExe = "$NginxDir\nginx.exe"
$NginxConf = "$NginxDir\conf\nginx.conf"
$DomainName = "erp.orderinvests.net"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Nginx Reverse Proxy Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Install Nginx if not already installed
if (-not $SkipInstall) {
    if (-not (Test-Path $NginxExe)) {
        Write-Host "Step 1: Installing Nginx..." -ForegroundColor Yellow
        Write-Host "Downloading Nginx for Windows..." -ForegroundColor White
        
        $nginxUrl = "http://nginx.org/download/nginx-1.24.0.zip"
        $zipFile = "$env:TEMP\nginx.zip"
        $extractDir = "$env:TEMP\nginx-extract"
        
        try {
            # Download Nginx
            Invoke-WebRequest -Uri $nginxUrl -OutFile $zipFile -UseBasicParsing
            Write-Host "Downloaded Nginx" -ForegroundColor Green
            
            # Extract
            if (Test-Path $extractDir) {
                Remove-Item $extractDir -Recurse -Force
            }
            Expand-Archive -Path $zipFile -DestinationPath $extractDir -Force
            
            # Move to C:\nginx
            if (Test-Path $NginxDir) {
                Remove-Item $NginxDir -Recurse -Force
            }
            Move-Item "$extractDir\nginx-1.24.0" $NginxDir -Force
            
            # Cleanup
            Remove-Item $zipFile -Force
            Remove-Item $extractDir -Recurse -Force
            
            Write-Host "[OK] Nginx installed to $NginxDir" -ForegroundColor Green
        } catch {
            Write-Host "[ERROR] Failed to install Nginx: $_" -ForegroundColor Red
            Write-Host "You can install Nginx manually from: http://nginx.org/en/download.html" -ForegroundColor Yellow
            exit 1
        }
    } else {
        Write-Host "[OK] Nginx already installed" -ForegroundColor Green
    }
} else {
    if (-not (Test-Path $NginxExe)) {
        Write-Host "[ERROR] Nginx not found at $NginxExe" -ForegroundColor Red
        Write-Host "Run without -SkipInstall to install Nginx" -ForegroundColor Yellow
        exit 1
    }
}

Write-Host ""

# Step 2: Backup existing nginx.conf
Write-Host "Step 2: Backing up existing configuration..." -ForegroundColor Yellow
if (Test-Path $NginxConf) {
    $backupFile = "$NginxConf.backup.$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item $NginxConf $backupFile -Force
    Write-Host "[OK] Backup created: $backupFile" -ForegroundColor Green
} else {
    Write-Host "[INFO] No existing configuration to backup" -ForegroundColor White
}

Write-Host ""

# Step 3: Create Nginx configuration
Write-Host "Step 3: Creating Nginx configuration..." -ForegroundColor Yellow

# Read the template from nginx_config.conf and create HTTP-only version
$nginxConfig = @"
# Nginx Configuration for PipLinePro
# Auto-generated by setup_nginx_reverse_proxy.ps1

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;
    
    # Logging
    access_log  logs/access.log;
    error_log   logs/error.log;
    
    # HTTP Server (Port 80) - Proxies to Flask app on port 5000
    server {
        listen       80;
        server_name  $DomainName;
        
        # Logging
        access_log  logs/erp_access.log;
        error_log   logs/erp_error.log;
        
        # Maximum upload size
        client_max_body_size 50M;
        
        # Proxy settings for Flask application
        location / {
            proxy_pass http://127.0.0.1:5000;
            proxy_set_header Host `$host;
            proxy_set_header X-Real-IP `$remote_addr;
            proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto `$scheme;
            proxy_set_header X-Forwarded-Host `$server_name;
            
            # WebSocket support (if needed)
            proxy_http_version 1.1;
            proxy_set_header Upgrade `$http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Timeouts
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
        
        # Static files (optional - if you want Nginx to serve static files directly)
        location /static/ {
            alias C:/PipLinePro/static/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}
"@

# Write configuration (without BOM - Nginx doesn't like BOM)
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($NginxConf, $nginxConfig, $utf8NoBom)
Write-Host "[OK] Configuration written to $NginxConf" -ForegroundColor Green

Write-Host ""

# Step 4: Test Nginx configuration
Write-Host "Step 4: Testing Nginx configuration..." -ForegroundColor Yellow
Push-Location $NginxDir
try {
    $testResult = & $NginxExe -t 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "[OK] Nginx configuration is valid" -ForegroundColor Green
        Write-Host $testResult -ForegroundColor White
    } else {
        Write-Host "[ERROR] Nginx configuration test failed:" -ForegroundColor Red
        Write-Host $testResult -ForegroundColor Red
        exit 1
    }
} catch {
    Write-Host "[ERROR] Failed to test Nginx configuration: $_" -ForegroundColor Red
    exit 1
} finally {
    Pop-Location
}

Write-Host ""

# Step 5: Configure Windows Firewall for port 80
Write-Host "Step 5: Configuring Windows Firewall..." -ForegroundColor Yellow
$firewallRule = Get-NetFirewallRule -DisplayName "PipLinePro HTTP Port 80" -ErrorAction SilentlyContinue
if ($firewallRule) {
    Write-Host "[INFO] Firewall rule already exists" -ForegroundColor White
    if (-not $firewallRule.Enabled) {
        Enable-NetFirewallRule -DisplayName "PipLinePro HTTP Port 80"
        Write-Host "[OK] Firewall rule enabled" -ForegroundColor Green
    }
} else {
    try {
        New-NetFirewallRule -DisplayName "PipLinePro HTTP Port 80" `
            -Direction Inbound `
            -LocalPort 80 `
            -Protocol TCP `
            -Action Allow `
            -Description "Allow inbound HTTP traffic for PipLinePro (Nginx)" | Out-Null
        Write-Host "[OK] Firewall rule created for port 80" -ForegroundColor Green
    } catch {
        Write-Host "[WARNING] Failed to create firewall rule: $_" -ForegroundColor Yellow
        Write-Host "You may need to manually allow port 80 in Windows Firewall" -ForegroundColor Yellow
    }
}

Write-Host ""

# Step 6: Start/Reload Nginx
Write-Host "Step 6: Starting Nginx..." -ForegroundColor Yellow
$nginxProcess = Get-Process -Name "nginx" -ErrorAction SilentlyContinue
if ($nginxProcess) {
    Write-Host "[INFO] Nginx is already running, reloading configuration..." -ForegroundColor White
    Push-Location $NginxDir
    & $NginxExe -s reload
    Pop-Location
    Write-Host "[OK] Nginx configuration reloaded" -ForegroundColor Green
} else {
    Push-Location $NginxDir
    Start-Process -FilePath $NginxExe -WindowStyle Hidden
    Pop-Location
    Start-Sleep -Seconds 2
    
    $nginxProcess = Get-Process -Name "nginx" -ErrorAction SilentlyContinue
    if ($nginxProcess) {
        Write-Host "[OK] Nginx started successfully" -ForegroundColor Green
    } else {
        Write-Host "[ERROR] Failed to start Nginx" -ForegroundColor Red
        Write-Host "Check the error log: $NginxDir\logs\error.log" -ForegroundColor Yellow
        exit 1
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Your application should now be accessible at:" -ForegroundColor Yellow
Write-Host "  http://$DomainName" -ForegroundColor White
Write-Host "  http://erp.orderinvests.net" -ForegroundColor White
Write-Host ""
Write-Host "Nginx is forwarding port 80 -> port 5000" -ForegroundColor White
Write-Host ""
Write-Host "To manage Nginx:" -ForegroundColor Cyan
Write-Host "  Start:   cd C:\nginx && .\nginx.exe" -ForegroundColor White
Write-Host "  Stop:    cd C:\nginx && .\nginx.exe -s stop" -ForegroundColor White
Write-Host "  Reload:  cd C:\nginx && .\nginx.exe -s reload" -ForegroundColor White
Write-Host "  Test:    cd C:\nginx && .\nginx.exe -t" -ForegroundColor White
Write-Host ""
Write-Host "IMPORTANT: Make sure your cloud provider firewall allows port 80!" -ForegroundColor Yellow
Write-Host ""

