"""Initial migration: Create all database tables

Revision ID: 4aed66069409
Revises: 
Create Date: 2025-12-08 16:12:41.459841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aed66069409'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_daily_balance_psp_date'), table_name='daily_balance')
    op.drop_index(op.f('idx_login_username_timestamp'), table_name='login_attempt')
    op.drop_index(op.f('idx_psp_allocation_psp_date'), table_name='psp_allocation')
    op.drop_index(op.f('idx_psp_devir_psp_date'), table_name='psp_devir')
    op.drop_index(op.f('idx_psp_kasa_top_psp_date'), table_name='psp_kasa_top')
    op.drop_index(op.f('idx_psp_track_date_psp'), table_name='psp_track')
    op.drop_index(op.f('idx_transaction_client_date'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_client_name'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_created_psp'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_currency_net_amount'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_date_category_currency'), table_name='transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_transaction_date_category_currency'), 'transaction', ['date', 'category', 'currency'], unique=False)
    op.create_index(op.f('idx_transaction_currency_net_amount'), 'transaction', ['currency', 'net_amount_try'], unique=False)
    op.create_index(op.f('idx_transaction_created_psp'), 'transaction', ['created_at', 'psp'], unique=False)
    op.create_index(op.f('idx_transaction_client_name'), 'transaction', ['client_name'], unique=False)
    op.create_index(op.f('idx_transaction_client_date'), 'transaction', ['client_name', 'date'], unique=False)
    op.create_index(op.f('idx_psp_track_date_psp'), 'psp_track', ['date', 'psp_name'], unique=False)
    op.create_index(op.f('idx_psp_kasa_top_psp_date'), 'psp_kasa_top', ['psp_name', 'date'], unique=False)
    op.create_index(op.f('idx_psp_devir_psp_date'), 'psp_devir', ['psp_name', 'date'], unique=False)
    op.create_index(op.f('idx_psp_allocation_psp_date'), 'psp_allocation', ['psp_name', 'date'], unique=False)
    op.create_index(op.f('idx_login_username_timestamp'), 'login_attempt', ['username', 'timestamp'], unique=False)
    op.create_index(op.f('idx_daily_balance_psp_date'), 'daily_balance', ['psp', 'date'], unique=False)
    # ### end Alembic commands ###

